[package]
name     = "copy-ami-tags-rs"
version  = "0.1.1"
authors  = ["Joseph Kordish <joe@unicornclouds.com>"]
readme   = "README.md"
license  = "The MIT License (MIT)"
keywords = [
  "aws",
  "ami",
  "packer"
]

[[bin]]
name = "copy-ami-tags"

[dependencies]
rusoto_core  = "0.31"
rusoto_ec2   = "0.31"
rusoto_sts   = "0.31"
serde_json   = "^1"
crossbeam    = "^0.3"
slog         = "2"
slog-term    = "2"
slog-async   = "2"
clippy       = { version="*", optional = true }

[features]
default=[]

[profile.release]
#panic            = "unwind"
#lto              = true
#debug            = false
#rpath            = false
opt-level        = 3
#debug-assertions = false
codegen-units    = 1
